// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApplication10.DataDB;

namespace WebApplication10.Migrations
{
    [DbContext(typeof(DataProjectContext))]
    partial class DataProjectContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:Collation", "SQL_Latin1_General_CP1_CI_AS")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WebApplication10.DataDB.Contact", b =>
                {
                    b.Property<int>("IdContacts")
                        .HasColumnType("int")
                        .HasColumnName("Id_Contacts");

                    b.Property<string>("Email")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("first_name");

                    b.Property<string>("HomePhone")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("home _phone");

                    b.Property<string>("HowComeUs")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("how_comeUs");

                    b.Property<int?>("IdTreat")
                        .HasColumnType("int")
                        .HasColumnName("id_treat");

                    b.Property<string>("LastName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("last_name");

                    b.Property<string>("MobilePhone")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("mobile_phone");

                    b.Property<string>("NumberPhone")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("number_phone ");

                    b.Property<string>("Remark")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("remark");

                    b.Property<bool>("Sem")
                        .HasColumnType("bit")
                        .HasColumnName("sem");

                    b.HasKey("IdContacts")
                        .HasName("PK__Contacts__86C6BBA370C5FA70");

                    b.ToTable("Contacts");
                });

            modelBuilder.Entity("WebApplication10.DataDB.TblAccount", b =>
                {
                    b.Property<int>("IdAccount")
                        .HasColumnType("int")
                        .HasColumnName("Id_account");

                    b.Property<int?>("Crdite")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DateTime")
                        .HasColumnType("datetime");

                    b.Property<int>("IdContacts")
                        .HasColumnType("int")
                        .HasColumnName("Id_Contacts");

                    b.Property<int>("IdTreat")
                        .HasColumnType("int")
                        .HasColumnName("Id_treat");

                    b.Property<int?>("Owes")
                        .HasColumnType("int");

                    b.Property<int?>("Pay")
                        .HasColumnType("int");

                    b.HasKey("IdAccount")
                        .HasName("PK__tbl_acco__741F0A2BBECAC350");

                    b.ToTable("tbl_account");
                });

            modelBuilder.Entity("WebApplication10.DataDB.TblAppointment", b =>
                {
                    b.Property<int>("IdAppointment")
                        .HasColumnType("int")
                        .HasColumnName("Id_appointment");

                    b.Property<DateTime?>("Date")
                        .HasColumnType("date");

                    b.Property<bool?>("Discount")
                        .HasColumnType("bit");

                    b.Property<int?>("Durction")
                        .HasColumnType("int");

                    b.Property<int?>("IdContacts")
                        .HasColumnType("int")
                        .HasColumnName("Id_Contacts");

                    b.Property<int?>("IdEmployee")
                        .HasColumnType("int")
                        .HasColumnName("Id_employee");

                    b.Property<int?>("IdTreat")
                        .HasColumnType("int")
                        .HasColumnName("Id_treat");

                    b.Property<string>("Remark")
                        .HasColumnType("text");

                    b.Property<bool?>("Remined")
                        .HasColumnType("bit");

                    b.Property<TimeSpan?>("Time")
                        .HasColumnType("time");

                    b.Property<bool?>("Wait")
                        .HasColumnType("bit");

                    b.HasKey("IdAppointment")
                        .HasName("PK__tbl_appo__D0F3704DB63FEDD6");

                    b.ToTable("tbl_appointments");
                });

            modelBuilder.Entity("WebApplication10.DataDB.TblEmployee", b =>
                {
                    b.Property<int>("IdEmployee")
                        .HasColumnType("int")
                        .HasColumnName("Id_employee");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("color");

                    b.Property<int>("IdTreat")
                        .HasColumnType("int")
                        .HasColumnName("Id_treat");

                    b.Property<string>("NameEmployee")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("name_employee");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("password");

                    b.Property<string>("Permission")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("permission");

                    b.HasKey("IdEmployee")
                        .HasName("PK__tbl_empl__285BF3F77F8FC4CA");

                    b.ToTable("tbl_employees");
                });

            modelBuilder.Entity("WebApplication10.DataDB.TblInquiry", b =>
                {
                    b.Property<int>("IdInquirie")
                        .HasColumnType("int")
                        .HasColumnName("Id_inquirie");

                    b.Property<bool?>("Done")
                        .HasColumnType("bit");

                    b.Property<int?>("From")
                        .HasColumnType("int");

                    b.Property<int>("IdAppointment")
                        .HasColumnType("int")
                        .HasColumnName("Id_appointment");

                    b.Property<string>("Remark")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("To")
                        .HasColumnType("int");

                    b.HasKey("IdInquirie")
                        .HasName("PK__tbl_inqu__57640B01E7A2A766");

                    b.ToTable("tbl_inquiries");
                });

            modelBuilder.Entity("WebApplication10.DataDB.TblLaser", b =>
                {
                    b.Property<int>("IdLaser")
                        .HasColumnType("int")
                        .HasColumnName("Id_laser");

                    b.Property<string>("Area")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("Date")
                        .HasColumnType("datetime");

                    b.Property<int?>("Energy")
                        .HasColumnType("int");

                    b.Property<int>("IdContacts")
                        .HasColumnType("int")
                        .HasColumnName("Id_Contacts");

                    b.Property<string>("Ms")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Reaction")
                        .HasColumnType("text");

                    b.Property<string>("SpotSize")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Spot_size");

                    b.HasKey("IdLaser")
                        .HasName("PK__tbl_lase__87E2B0625B449B8E");

                    b.ToTable("tbl_laser");
                });

            modelBuilder.Entity("WebApplication10.DataDB.TblRoom", b =>
                {
                    b.Property<int>("IdRoom")
                        .HasColumnType("int")
                        .HasColumnName("Id_room");

                    b.Property<string>("NameRoom")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Name_room");

                    b.Property<int?>("Treats")
                        .HasColumnType("int");

                    b.HasKey("IdRoom")
                        .HasName("PK__tbl_room__46CA677C95FF13E0");

                    b.ToTable("tbl_room");
                });

            modelBuilder.Entity("WebApplication10.DataDB.TblSpecialEvent", b =>
                {
                    b.Property<int>("IdSpecialEvents")
                        .HasColumnType("int")
                        .HasColumnName("Id_special_events");

                    b.Property<DateTime>("Date")
                        .HasColumnType("date")
                        .HasColumnName("date");

                    b.Property<TimeSpan?>("EndHour")
                        .HasColumnType("time");

                    b.Property<int>("IdEmployee")
                        .HasColumnType("int")
                        .HasColumnName("Id_employee");

                    b.Property<TimeSpan?>("StartHour")
                        .HasColumnType("time");

                    b.Property<bool>("Work")
                        .HasColumnType("bit");

                    b.HasKey("IdSpecialEvents")
                        .HasName("PK__tbl_spec__77988C6AD112F0B5");

                    b.ToTable("tbl_special_events");
                });

            modelBuilder.Entity("WebApplication10.DataDB.TblTreat", b =>
                {
                    b.Property<int>("IdTreat")
                        .HasColumnType("int")
                        .HasColumnName("Id_treat");

                    b.Property<string>("NameTreat")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("nameTreat");

                    b.HasKey("IdTreat")
                        .HasName("PK__tbl_trea__C3F330BCB802BCFA");

                    b.ToTable("tbl_treat");
                });

            modelBuilder.Entity("WebApplication10.DataDB.TblWorkHour", b =>
                {
                    b.Property<int>("IdWorkHours")
                        .HasColumnType("int")
                        .HasColumnName("Id_work_hours");

                    b.Property<int?>("Day")
                        .HasColumnType("int");

                    b.Property<TimeSpan?>("EndHour")
                        .HasColumnType("time");

                    b.Property<int?>("IdEmployee")
                        .HasColumnType("int")
                        .HasColumnName("Id_employee");

                    b.Property<bool?>("ReglarWork")
                        .HasColumnType("bit");

                    b.Property<int?>("Shift")
                        .HasColumnType("int");

                    b.Property<TimeSpan?>("StartHour")
                        .HasColumnType("time");

                    b.HasKey("IdWorkHours")
                        .HasName("PK__tbl_work__66F155F508FA8686");

                    b.ToTable("tbl_work_hours");
                });
#pragma warning restore 612, 618
        }
    }
}
